"""Guard: the Dockerfiles are what the dependency graph says they are.

A hand-maintained list of what to copy drifts from the graph silently, and the drift shows up as a
build failing on somebody else's machine. So the files are generated and this refuses the
difference.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def test_the_dockerfiles_match_the_dependency_graph() -> None:
    result = subprocess.run(
        [sys.executable, str(ROOT / "scripts" / "render_dockerfiles.py"), "--check"],
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, result.stdout + result.stderr


def test_every_app_has_a_rendered_dockerfile() -> None:
    sys.path.insert(0, str(ROOT / "scripts"))
    from render_dockerfiles import APPS

    for app in APPS:
        dockerfile = ROOT / "apps" / app / "Dockerfile"
        assert dockerfile.is_file(), f"apps/{app}/Dockerfile is not rendered"
        text = dockerfile.read_text()
        assert "GENERATED by scripts/render_dockerfiles.py" in text
        assert "USER redteam" in text, "images do not run as root"
