"""Render each app's Dockerfile from the workspace dependency graph.

Hand-maintained COPY lists drift from the graph silently, until a build fails on a machine that is
not yours. So they are generated, and `tests/guards/test_dockerfiles.py` fails if what is committed
differs from what this produces.

The generation is also what keeps the isolation guarantees honest. Only an app's closure is copied
in, so an image carries exactly the packages its app depends on -- not by discipline but because the
file that would put anything else there is derived from the graph.

    uv run python scripts/render_dockerfiles.py          # write
    uv run python scripts/render_dockerfiles.py --check  # compare
"""

from __future__ import annotations

import sys
import tomllib
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

PYTHON_IMAGE = "python:3.12-slim"
UV_IMAGE = "ghcr.io/astral-sh/uv:0.7.10"
"""Pinned, because an unpinned tool image is a build that changes under you."""

SOURCE = "https://github.com/Alquimia-ai/red-teaming"
"""What the images name as their source. GitHub's container registry files an image under the
repository the label names, which is what makes it one of the repository's packages."""

DIST_PREFIX = "red-teaming-"


@dataclass(frozen=True)
class App:
    dist: str
    description: str
    """One phrase, for the image's description label."""

    why: str
    """One or two lines, as a Dockerfile comment, on what this image is for and what it must not
    carry."""

    entrypoint: str | None = None
    """The console script a job image runs. Exclusive with `service`."""

    service: str | None = None
    """The ASGI application a service image serves, as `module:attribute`."""

    port: int = 8080


APPS: dict[str, App] = {
    "api": App(
        dist="red-teaming-api",
        description="The red-teaming API: accepts runs, freezes specs, launches runners",
        service="redteam_api.main:app",
        why=(
            "The HTTP gate. It validates, freezes, launches, publishes and reads, and it does no\n"
            "# work: it carries no target adapter, no knowledge client and no model. It does\n"
            "# carry the catalogue package, so a bundle is validated and published synchronously."
        ),
    ),
    "runner": App(
        dist="red-teaming-runner",
        description="The red-teaming runner: one run, from generation to manifest",
        entrypoint="redteam-runner",
        why=(
            "One run, to completion, then exit. The only image where generation and conduction\n"
            "# meet: it carries the knowledge client, the judges, the target adapters and the\n"
            "# engine, and serves no HTTP."
        ),
    ),
}


def _dist_to_path() -> dict[str, str]:
    return {
        tomllib.loads(p.read_text())["project"]["name"]: f"packages/{p.parent.name}"
        for p in ROOT.glob("packages/*/pyproject.toml")
    }


def _dist_of(requirement: str) -> str:
    """The distribution a requirement names, without extras, markers or a version."""
    return requirement.split(";")[0].split("[")[0].split(">")[0].split("=")[0].split("<")[0].strip()


def closure(app_dir: str) -> list[str]:
    """Every workspace package the app depends on, transitively, as repository paths."""
    dist_to_path = _dist_to_path()
    paths: set[str] = set()
    frontier = [app_dir]
    while frontier:
        deps = tomllib.loads((ROOT / frontier.pop() / "pyproject.toml").read_text())["project"].get(
            "dependencies", []
        )
        for raw in deps:
            path = dist_to_path.get(_dist_of(raw))
            if path and path not in paths:
                paths.add(path)
                frontier.append(path)
    return sorted(paths)


def render(app: str) -> str:
    spec = APPS[app]
    paths = closure(f"apps/{app}")
    manifests = "\n".join(f"COPY {p}/pyproject.toml {p}/" for p in paths)
    sources = "\n".join(f"COPY {p}/src/ {p}/src/" for p in paths)
    if spec.service:
        run = f'CMD ["uvicorn", "{spec.service}", "--host", "0.0.0.0", "--port", "{spec.port}"]'
        expose = f"EXPOSE {spec.port}\n\n"
    else:
        run = f'ENTRYPOINT ["{spec.entrypoint}"]'
        expose = ""
    return f"""# red-teaming-{app}
#
# GENERATED by scripts/render_dockerfiles.py -- edit that, not this.
#
# {spec.why}
#
# Built from the repository root: the workspace resolves as one lock, and only this app's
# dependency closure is copied in. What is absent from the image is a structural guarantee, not a
# convention.
FROM {PYTHON_IMAGE}

LABEL org.opencontainers.image.source="{SOURCE}" \\
      org.opencontainers.image.title="red-teaming-{app}" \\
      org.opencontainers.image.description="{spec.description}"

ENV PYTHONUNBUFFERED=1 \\
    UV_COMPILE_BYTECODE=1 \\
    UV_LINK_MODE=copy

WORKDIR /app
COPY --from={UV_IMAGE} /uv /uvx /usr/local/bin/

# Manifests first, in their own layer, so dependency resolution caches independently of source
# edits.
COPY pyproject.toml uv.lock ./
COPY apps/{app}/pyproject.toml apps/{app}/
{manifests}

RUN uv sync --frozen --package {spec.dist} --no-dev --no-install-workspace

# Then the sources for the workspace members this app actually uses.
COPY apps/{app}/src/ apps/{app}/src/
{sources}

RUN uv sync --frozen --package {spec.dist} --no-dev

# Nothing here runs as root: the process writes to the store over the network and to nowhere on
# disk it does not own.
RUN groupadd --gid 1000 redteam && useradd --uid 1000 --gid 1000 --create-home redteam
USER redteam
ENV PATH="/app/.venv/bin:$PATH"

{expose}{run}
"""


def main(check: bool) -> int:
    drifted: list[str] = []
    for app in APPS:
        path = ROOT / "apps" / app / "Dockerfile"
        rendered = render(app)
        if check:
            if not path.exists() or path.read_text() != rendered:
                drifted.append(str(path.relative_to(ROOT)))
        else:
            path.write_text(rendered)
            print(f"  wrote {path.relative_to(ROOT)}")
    if drifted:
        print("Dockerfiles have drifted from the dependency graph:")
        for name in drifted:
            print(f"  {name}")
        print("Run: uv run python scripts/render_dockerfiles.py")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main("--check" in sys.argv))
